module.exports=function(db){
 const now=new Date().toISOString();
 const pimg=['/images/catalog/phone.svg','/images/catalog/laptop.svg','/images/catalog/bag.svg','/images/catalog/shirt.svg','/images/catalog/chair.svg','/images/catalog/powerbank.svg','/images/catalog/speaker.svg','/images/catalog/watch.svg'];
 const simg=['/images/catalog/camera.svg','/images/catalog/laptop.svg','/images/catalog/chair.svg','/images/catalog/shirt.svg'];
 const products=[
  ['Budget Android Phone','Phones & Tablets','Affordable smartphone option for everyday calls, school and work.',85000],['Phone Protective Case','Phones & Tablets','Protective case for compatible smartphones.',3500],['Tempered Glass Screen Protector','Phones & Tablets','Screen protection for compatible smartphones.',2500],['USB-C Power Adapter','Electronics','Compact wall charger for compatible USB-C devices.',6500],['Bluetooth Headset','Electronics','Wireless headset for calls, meetings and entertainment.',14500],['Rechargeable Table Fan','Home','Rechargeable fan for rooms, shops and small offices.',18000],['LED Bulb Pack','Home','Energy-saving LED bulbs for home and business spaces.',7500],['Extension Cable','Electronics','Practical extension cable for home and office use.',6000],['Padlock Heavy Duty','Hardware','Heavy-duty padlock for gates, shops, stores and lockers.',6500],['Key Cutting Blank Set','Hardware','Assorted key blanks for locksmith and key-cutting work.',9000],['Trowel','Building Materials','Masonry trowel for plastering and building work.',4500],['Frame Saw','Building Materials','Hand frame saw for wood cutting and workshop jobs.',7000],['Floor Mop','Home','Reusable floor mop for home, office and shop cleaning.',5500],['School Sandals','Fashion','Durable everyday sandals for school and casual use.',9000],['Plain T-Shirt','Fashion','Simple everyday T-shirt available in multiple sizes.',7000],['Women Fashion Top','Fashion','Casual fashion top for everyday wear.',9500],['Men Casual Trousers','Fashion','Everyday trousers for work and casual outfits.',15000],['Travel Duffle Bag','Fashion','Practical travel bag for short trips and everyday use.',18000],['Rechargeable Emergency Light','Home','Portable light for homes, shops and power interruptions.',12000],['Small Business Calculator','Office','Simple calculator for shops and daily business records.',4500],['Receipt Book','Office','Physical receipt book for small business record keeping.',2500],['A4 Notebook','Office','Notebook for school, work, planning and business records.',3000],['Packing Tape','Business Supplies','Strong tape for packaging customer orders and parcels.',2500],['Food Storage Containers','Home','Reusable containers for food storage and small food businesses.',8500],['Water Dispenser Bottle','Home','Reusable bottle suitable for water storage and dispensing.',6500],['Basic Tool Kit','Hardware','Starter tool set for common household and small repair jobs.',22000],['Measuring Tape','Hardware','Measuring tape for building, furniture and repair work.',3500],['Work Gloves','Hardware','Protective gloves for workshop, cleaning and building tasks.',4000],['Small Bluetooth Speaker','Electronics','Portable speaker for home, events and outdoor use.',12000],['USB Rechargeable Torch','Electronics','Portable rechargeable torch for home and outdoor use.',7500]
 ];
 const services=[
  ['Key Cutting & Locksmith Service','Repairs','Key cutting, lock support and basic locksmith assistance.',3000],['Building Material Sourcing','Building Services','Help source basic building materials and arrange local supply.',10000],['Home Painting','Home Services','Interior and exterior painting for homes, shops and offices.',25000],['Masonry Work','Building Services','Block work, plastering and basic masonry jobs.',30000],['Carpentry Repairs','Home Services','Furniture and household woodwork repairs.',20000],['Phone Accessories Setup','Technology','Phone setup, accessories fitting and basic configuration.',5000],['POS Setup Assistance','Business Support','Basic POS and small-shop setup guidance.',8000],['Small Shop Branding','Creative Services','Simple signage, flyer and shop branding package.',18000],['WhatsApp Business Setup','Business Support','Set up a WhatsApp Business profile, catalogue and basic responses.',10000],['Business Page Setup','Business Support','Set up a professional online business presence and shareable page.',15000],['Product Photography Basic','Media','Simple product photos suitable for marketplace listings.',10000],['Flyer Design Basic','Creative Services','Simple promotional flyer for small businesses and events.',7000],['Price List Design','Creative Services','Clean price list for WhatsApp, print or social media.',6000],['Typing & Printing Assistance','Digital Services','Typing, formatting and preparing documents for printing.',3000],['Online Application Assistance','Digital Services','General help completing online forms and application documents.',5000],['Home Delivery - Local','Logistics','Local pickup and delivery service subject to location.',3000],['Errand Service','Logistics','Local errands and collection/drop-off assistance.',5000],['Clothing Pickup & Delivery','Logistics','Local pickup and return support for clothing and laundry.',4000],['Basic Business Record Setup','Business Support','Simple sales, expense and customer record setup.',10000],['Small Business Advice Session','Business Support','Practical session for pricing, customer handling and simple business organisation.',8000]
 ];
 const ip=db.prepare(`INSERT OR IGNORE INTO products(public_id,owner_id,owner_name,owner_username,name,category,description,price,delivery_price,payment_method,image_data,featured,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`);
 products.forEach((x,i)=>ip.run('brave-extra-product-'+String(i+1).padStart(3,'0'),'BRAVE_SHOWCASE','UNIQUE BRAVE','',x[0],x[1],x[2],x[3],500,'pay_on_delivery',pimg[i%pimg.length],0,'active',now,now));
 db.prepare("UPDATE products SET delivery_price=500 WHERE owner_id='BRAVE_SHOWCASE' AND (delivery_price IS NULL OR delivery_price=0)").run();
 const is=db.prepare(`INSERT OR IGNORE INTO services(public_id,owner_id,owner_name,owner_username,name,category,description,price,payment_method,image_data,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)`);
 services.forEach((x,i)=>is.run('brave-extra-service-'+String(i+1).padStart(3,'0'),'BRAVE_SHOWCASE','UNIQUE BRAVE','',x[0],x[1],x[2],x[3],'pay_after_service',simg[i%simg.length],'active',now,now));
};
